### ISSUE TITLE
Recurring Invoices are not generating Invoices on Docker

### ISSUE THREAD

**Issue by Akjo4712** [invoiceninja/dockerfiles#242]
**What version of Invoice Ninja are you running?** 
v5.0.39

**What environment are you running?**
Docker

**Have you checked log files (storage/logs/)**
Found nothing related.

**Have you searched existing issues?**
Yes

**Have you reported this to Slack/forum before posting?**
No

**Describe the bug**
On my Docker installation i have some recurring invoices. They show up as over due, but there are no invoices created.

**Steps To Reproduce**
Create recurring invoice  
Wait for next send date  
Nothing happens

**Expected behavior**
On Next send date there should be a new invoice for that customer

**Additional context**
This didn‘t work bevore, so i think nothing related to a recent update.

**Comment by Akjo4712** [comment]
@turbo124, until we get this fixed, is there a Command i can run manually so the Invoices are being created?

**Comment by turbo124** [comment]
You could try something like this

```bash
docker-compose exec app php artisan schedule:run
```

**Comment by Akjo4712** [comment]
Hi! I just updated to v5.0.41-C35, release notes state some fix for recurring Invoices, but no Invoice was created since i updated. So i just ran your suggested command, which also did nothing. Any suggestions how to proceed?

**Comment by turbo124** [comment]
@Akjo4712 we are currently having a third party review our dockerfiles. Once we are happy with a solution we'll update you here.

**Comment by turbo124** [comment]
fixed in new docker file

**Comment by Akjo4712** [comment]
Hi! Just made a fresh install with v5.0.44-C37. Up and running for about 3 Hours. The Recurring Invoices are still not generated. Is this Job executed only once a day, or am i missing something?

**Comment by turbo124** [comment]
the scheduler runs every minute, and the recurring cron runs every hour..

My suggestion would be to bring the container up without the -d ie ```docker-compose up``` and then watch the logging

**Comment by Akjo4712** [comment]
The Cron Container seems to run without any issues, see the Screenshot below. Also the normal Invoice Mails, which i think are also handled by the Cron, are all sent timely.

![image](https://user-images.githubusercontent.com/65533611/104002571-8f423f00-51a1-11eb-935f-df2c7f7bac64.png)

**Comment by turbo124** [comment]
Not sure about this, i cannot recreate this issue. can you confirm your docker-compose.yml is identical to the repo?

**Comment by Akjo4712** [comment]
I just also found out, that the force update screen, which should show the running and available version is not getting updated. In one of your announcments in the forum there is a hint, that this is also handled by the cron. So it seems as if the cron is not executed at all.
![image](https://user-images.githubusercontent.com/65533611/104153316-5349ec80-53e2-11eb-81b2-551215476bd0.png)

With the new Version, I just saw the following Log output, which states, that the Job was executed. I just created a new Recurring Invoice, I will have a look if it is working now.
![image](https://user-images.githubusercontent.com/65533611/104153713-5396b780-53e3-11eb-84f9-d10ab2b1e0c6.png)

Recent Logs only consist of Messages like `[2021-01-08 19:29:05] production.INFO: company1` just with another Timestamp. 
![image](https://user-images.githubusercontent.com/65533611/104153628-1fbb9200-53e3-11eb-976f-3a61f97ae42c.png)
 
My compose.yml is not exactly the same, but that shouldn't matter I think.
version: '3.7'

```
services:
  server:
    image: nginx
    restart: always
    env_file: /share/Container/container-station-data/lib/docker/volumes/invoiceninja_config/env
    volumes:
      - /share/Container/container-station-data/lib/docker/volumes/invoiceninja_config/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      -  public:/var/www/app/public
      -  storage:/var/www/app/storage
    depends_on:
      - app
    networks:
      - invoiceninja
      - nginx_reverseproxy
  app:
    image: invoiceninja/invoiceninja:5
    restart: always
    cap_add:
      - SYS_ADMIN
    env_file: /share/Container/container-station-data/lib/docker/volumes/invoiceninja_config/env
    volumes:
      - public:/var/www/app/public
      - storage:/var/www/app/storage
    depends_on:
      - db
    networks: 
      - invoiceninja  
  db:
    image: mysql:5
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=*****
      - MYSQL_USER=*****
      - MYSQL_PASSWORD=*****
      - MYSQL_DATABASE=*****
    volumes:
      - mysql:/var/lib/mysql:rw
    networks:
      - invoiceninja
  cron:
    image: invoiceninja/invoiceninja:5
    env_file: /share/Container/container-station-data/lib/docker/volumes/invoiceninja_config/env
    volumes:
      - /share/Container/container-station-data/lib/docker/volumes/invoiceninja_config/cron.sh:/usr/local/bin/cron.sh
      - public:/var/www/app/public
      - storage:/var/www/app/storage
    command:
    - cron.sh
    networks:
    - invoiceninja
    depends_on:
    - app
volumes:
  mysql:
  public:
  storage:
networks:
  invoiceninja:
  nginx_reverseproxy:
    external: true
```

**Comment by Akjo4712** [comment]
For full reference, here the env File.

```
APP_URL=*****
APP_KEY=*****
MULTI_DB_ENABLED=false
DB_HOST1=*****
DB_USERNAME1=*****
DB_PASSWORD1=*****
DB_DATABASE1=*****
PHANTOMJS_PDF_GENERATION=false
MAIL_MAILER=smtp
MAIL_HOST=*****
MAIL_PORT=25
MAIL_USERNAME=*****                                                                                                                                                                                                                                                                                            
MAIL_PASSWORD=*****                                                                                                                                                                                                                                                                                     
MAIL_ENCRYPTION=TLS
MAIL_FROM_NAME=*****
MAIL_FROM_ADDRESS=*****
APP_DEBUG=false
```

**Comment by Akjo4712** [comment]
With the newly created Recurring Invoice it is now working. Is it possible, that there is a Problem with previously created recurring Invoices? Some missing/null Field in the Database or other dependencies?

**Comment by turbo124** [comment]
There is an issue with the query that gets the recurring invoices,i have a fix for this in the v5-develop branch.

**Comment by Akjo4712** [comment]
Nice to hear! Great work you are doing with Invoice Ninja!
